spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.rivmavaifjpjrifqlzzk
    password: jx%9!@i*kEw?r9K
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
  jooq:
    sql-dialect: POSTGRES
