spring:
  application:
    name: k9x-backend
  banner:
    location: classpath:banner.txt
  profiles:
    active: '@spring.profiles.active@'
  autoconfigure:
    exclude:
      - org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration
      - org.springframework.boot.mongodb.autoconfigure.MongoReactiveAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.DataMongoReactiveAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.DataMongoRepositoriesAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.DataMongoReactiveRepositoriesAutoConfiguration

server:
  port: 4000

k9x-backend:
  timeoutValue: 5000
  security:
    jwt-secret: "change-me-to-a-32-byte-minimum-secret"
    jwt-public-jwk-n: "vMB8sa7i5JUTgnd8FNsoVL6-5-0DVGYmUdkdSnMetRpJb7rUi1JyLYCGO0IYG3uzZ-5Bj13z72hWeHc-NfFT27N8OuHriAjp5jdEtUUOYIiZCQl_C1Asg_eTJB-DaRGIZjIXlx_nwYXc4fmDaLUaIFdSLkCHCbdYrKuF4GcPMCbIdJehhSyeUEeH4yjy14YagMxR-k2DNRoWYhpKtyw4VXOA5uLdZoev5q-5B3HRMLknF73GyussSvh4yV9MZCcSNL6rWHKZ9sl_Ap2w15tWkrUhTc-iD8H9ygqAq46_H9ypLouw2OuLTg6hDe5sjfnsTPlmBzAZJF4UI-p2LqUBFw"
    jwt-public-jwk-e: "AQAB"
    jwt-cache-ttl-minutes: 15
    google-client-ids: "32555940559.apps.googleusercontent.com"
  info:
    app:
      name: '@project.artifactId@'
      version: '@project.version@'
  deploy:
    tech: in-memory
