package com.k9x.application.notifications.port;

import com.k9x.application.notifications.port.payload.SaveEventNotificationPersistencePayload;

public interface SaveEventNotificationPersistencePort {

    /**
     * Stores the announcement and links it to every event it applies to. Its identifier is generated by the
     * database and does not leave the adapter — nothing above the port refers to an announcement by id.
     */
    void save(SaveEventNotificationPersistencePayload payload);
}
