-- =============================================================================
-- Ob World Cup 2026: k9x schema data (dogs, judges, competition, stages, events),
-- sourced from ResultsqualificationWC_HCA_TeamvsIndv_ENDresults.xlsx (tabs '1'..'120'
-- for dogs, 'General' for judges).
--
-- This is a one-off data script, NOT a Flyway migration/seed: run it manually
-- against a target database after the schema/seed migrations have been applied.
-- Run this file BEFORE ob_wc_2026_obdx.sql, which references these rows via FK.
--
-- Skipped tabs 119 and 120: placeholder/test rows with no Reg.number
-- ('None' / 'None 2', handler 'Test' / 'Test 2', country 'NA').
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Dogs
-- ---------------------------------------------------------------------------
INSERT INTO k9x.dogs (id, identity, breed, name, image, owner, creator, country, team, handler,
                      last_update, created_at, deleted_at, three_fci_generations_confirmed)
VALUES ('wc2026-dog-1', 'G1-3.206.225', 'AUSTRALIAN_KELPIE', 'Yaparoos Deadly Mr Deeks', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'NL', 'Netherlands', 'Nathalie Hoeppermans', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-2', 'SHSB 792640', 'MALINOIS', 'Kito-Kaan vom Goldschakal', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'CH', 'Switzerland', 'Susan Jenny', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-3', 'ÖHZB BORC 4789', 'BORDER_COLLIE', 'Seven up Mind the Dog', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AT', 'Austria', 'Surlina, Kristina', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-4', 'LOF B;BEL 320421', 'BELGIAN_SHEPHERD_TERVUREN', 'ROXANNE DE LA FONTAINE SAINT LOUIS', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'FR', 'France', 'Gwenaëlle CORNILLET',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-5', 'CMKU/BOC/14423/-20/19/23', 'BORDER_COLLIE', 'Every Kingdom Shock Wave', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'CZ', 'Czechia', 'Ivana Šimůnková',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-6', 'LOE 2396529', 'BORDER_COLLIE', 'GINGERBELL KINDLE DWINDLE', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'ES', 'Spain', 'CÉSAR JOSÉ ARROYO GONZÁLEZ', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-7', 'LO20138895', 'BORDER_COLLIE', 'INTERFORCE TSUNAMI', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'CIRELLI EMILIANA', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-8', 'LOF 61569/7089', 'BORDER_COLLIE', 'ALBA''EYES RILEY', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FR', 'France', 'Christelle CLASTRES', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-9', 'NO32722/20', 'BORDER_COLLIE', 'Chocomate`s Thomas Made 4 work', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'NO', 'Norway', 'Hege Johnsen', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-10', 'LV-BOK-141/22', 'BORDER_COLLIE', 'Fuksiya', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'LV', 'Latvia', 'Tatiana Shtubei', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-11', 'VDH/ZBrH BOC 26368', 'BORDER_COLLIE', 'Mind the Dog Xtra Ice', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DE', 'Germany', 'Marvin Hahn', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-12', 'se33344/2020', 'GOLDEN_RETRIEVER', 'Stjärnglimtens Önskade Jax', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'SE', 'Sweden', 'Tina Hansson',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-13', 'LOSH 1270440', 'BORDER_COLLIE', 'ECLATS D''ETOILE RSHARKO DIT REPLAY', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'BE', 'Belgium', 'PEETERMANS CHRISTEL',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-14', 'ÖHZB SR 3307', 'RIESENSCHNAUZER', 'Cobra con todos-los-santos', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AT', 'Austria', 'Florschütz, Petra', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-15', 'I-100087', 'BORDER_COLLIE', 'Smart as a Whip DON''T STOP', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PL', 'Poland', 'Dominika Stępień', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-16', 'LOP600708', 'BORDER_COLLIE', 'SMART AS A WHIP DOUBLE TROUBLE', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PT', 'Portugal', 'PAULO ALVES', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-17', 'I-85463', 'BORDER_COLLIE', 'BIG SHOT IN FISH EYE', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PL', 'Poland', 'Magdalena Stodułko', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-18', 'Z Reg/BOC/12384/-19/17', 'BORDER_COLLIE', 'U´Angela Never Never Land', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'CZ', 'Czechia', 'Anna Musilová',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-19', 'NO32721/20', 'BORDER_COLLIE', 'Chocomate''s Wikki Perfect 2 work', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'NO', 'Norway', 'Monika Kvernberg',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-20', 'LOE 2598022', 'LABRADOR_RETRIEVER', 'ELECTRA DE FRAGUA MAYOR', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'ES', 'Spain', 'JESÚS MARTÍN GONZÁLEZ', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-21', 'Regv1583/2022', 'BORDER_COLLIE', 'Push It', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SE', 'Sweden', 'Susy Tvärnstedt', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-22', 'I-118325', 'BORDER_COLLIE', 'SIGMA Du Domaine D''Oranna', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PL', 'Poland', 'Anna Butryn', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-23', 'DK03677/2016', 'BORDER_COLLIE', 'Spotting Merry Polka', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DK', 'Denmark', 'Camilla Carmen Christensen', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-24', 'regv1736/2021', 'BORDER_COLLIE', 'All In For Magic', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SE', 'Sweden', 'Lotta Rubom', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-25', 'FI55745/17', 'GOLDEN_RETRIEVER', 'Pendolinon Little Soulmate', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Tiina Palmu', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-26', 'Col. 1839/18', 'BORDER_COLLIE', 'Enzo From Camilland''s', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'HU', 'Hungary', 'Nora Bartha', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-27', 'DK06129/2014', 'BORDER_COLLIE', 'High Working BC Bonus', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DK', 'Denmark', 'Siri Renée Richter Jungersen',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-28', 'ER25167/18', 'BORDER_COLLIE', 'Unlimited Star Gwen', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Maarit Hellman', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-29', 'Col.1841/18', 'BORDER_COLLIE', 'Elijah From Camilland''s', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'HU', 'Hungary', 'Zsuzsanna Földi', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-30', 'JKC BCL 00641/20', 'BORDER_COLLIE', 'VICTOR INFINITY OF GRAND CYPRESS JP', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'JP', 'Japan', 'Tomoko Adachi',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-31', 'SHSB 794288', 'BORDER_COLLIE', 'Xayu of Shadowman', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'CH', 'Switzerland', 'Janine Götz', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-32', 'LO1944722', 'GOLDEN_RETRIEVER', 'WILL SMITH', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'PERRETTI DEBORA JEANNE MARIJA',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-33', 'EST-00520/20', 'BORDER_COLLIE', 'TENDING ZAHIRA', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'EE', 'Estonia', 'Anne Tammiksalu', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-34', 'LOSH - 01321121', 'WHITE_SWISS_SHEPHERD_DOG', 'Tea White of Linde''s White Wolves', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'BE', 'Belgium', 'MEUNIER MEGAN',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-35', 'REGV1288/2021', 'BORDER_COLLIE', 'All In For Crei-Zi', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'NO', 'Norway', 'Monica Wickstrøm', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-36', 'SPKP 1668', 'BORDER_COLLIE', 'Doriel Reesheja', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SK', 'Slovakia', 'Dagmar Hajdeckerová', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-37', 'FI28641/19', 'LABRADOR_RETRIEVER', 'Brufinn Yazzy Queen', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Maarit Hankaniemi', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-38', 'SHSB 766480', 'BORDER_COLLIE', 'Wonderful Life del Mulino Prudenza', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'CH', 'Switzerland', 'Laura Cayetano',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-39', 'LO2131009', 'BORDER_COLLIE', 'GINGERBELL NE BIS IN IDEM', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'BARTELLONI LUCA', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-40', 'LOP640045', 'BORDER_COLLIE', 'AMORA DO SONHO DO CÃO', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PT', 'Portugal', 'JOSE RICARDO SILVA MACEDO', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-41', 'LŠVK BS 2883/22', 'BERNESE_MOUNTAIN_DOG', 'Ursula Baltų Valdovas', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'LT', 'Lithuania', 'Laurynas Janavičius',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-42', 'DRC-G 1941250', 'GOLDEN_RETRIEVER', 'Copper''s Sparkling Fix you Kamikaze', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'DE', 'Germany', 'Karolin Zewe',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-43', 'NO47162/21', 'BORDER_COLLIE', 'Luba', NULL, 'k9x.support@gmail.com', 'k9x.support@gmail.com',
        'NO', 'Norway', 'Nora Foshaug', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-44', 'ROI 20/6257', 'BORDER_COLLIE', 'Gingerbell Eager Moose', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AT', 'Austria', 'Bachl-Steiner, Susanne', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-45', 'ADLA 003659', 'BORDER_COLLIE', 'Tending Xcalibur', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AM', 'Armenia', 'Varvara Bolshakova', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-46', 'LLOF 36526/6191', 'BORDER_COLLIE', 'LUCKY DE LA BERGERIE DE MORGANE', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'FR', 'France', 'Claude GUZZO',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-47', 'JKC BCL-00342/21', 'BORDER_COLLIE', 'GROWTH TANGO OF OHANA JP', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'JP', 'Japan', 'Yukari Horie', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-48', 'regv1403/2021', 'BORDER_COLLIE', 'Vallhunden MR Hyde', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SE', 'Sweden', 'Niina Svartberg', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-49', 'ČLP/GR/23543/2023', 'GOLDEN_RETRIEVER', 'Always Spot On Sparkling Mountains', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'CZ', 'Czechia', 'Renáta Sinerová',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-50', 'I-118174', 'BORDER_COLLIE', 'High Tension LET''S SHINE', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PL', 'Poland', 'Joanna Hewelt', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-51', 'VDH/ZBrH BOC 25347', 'BORDER_COLLIE', 'Nature mind Flake', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DE', 'Germany', 'Regina Herrmann', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-52', 'regv1080/2016', 'BORDER_COLLIE', 'Vallhunden Chapman', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SE', 'Sweden', 'Karin Fischer Kristansson', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-53', 'DK16010/2021', 'BORDER_COLLIE', 'High working BC Rayforce Jett', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'NL', 'Netherlands', 'Andrea van Egmond',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-54', 'LO19149893', 'BORDER_COLLIE', 'WELSHRIVERDEE ADRENALINE', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'ASIRELLI CHRISTIAN', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-55', 'NO36752/18', 'BORDER_COLLIE', 'Hind Paw`s Timm', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'NO', 'Norway', 'Beth Helen Vilbo', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-56', 'FI12174/21', 'GOLDEN_RETRIEVER', 'Saukonkiven Pohjantähti', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Niina Sorjonen', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-57', 'REGV1234/2019', 'BORDER_COLLIE', 'Kajsaligans Odds', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SE', 'Sweden', 'Sandra Gisslar', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-58', 'SHSB 760462', 'BORDER_COLLIE', 'Aimy Seven Sisters', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'CH', 'Switzerland', 'Monika Ballerini', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-59', 'DK10540/2023', 'BORDER_COLLIE', 'Lemonlove Lotus Supreme', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DK', 'Denmark', 'Louisa Wibroe', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-60', 'FI49816/19', 'BORDER_COLLIE', 'Tending Zipper', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Oili Huotari', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-61', 'LO2092485', 'BORDER_COLLIE', 'MIND THE DOG QUADRIFOGLIO', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'BOSSI SILVANA', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-62', 'LOP635076', 'MALINOIS', 'CHITA FROM GENESIS OF TOP GUN', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PT', 'Portugal', 'FRANCISCO ALBERTO ANTUNES VAN DIJK',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-63', 'SPKP 1378/23', 'BORDER_COLLIE', 'Infinita Esperanza Dynamic Quest', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'SK', 'Slovakia', 'Miriam Burajová',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-64', 'ÖHZB BORC 4628', 'BORDER_COLLIE', 'Firehillborders Jasper Frost', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'AT', 'Austria', 'Mayrhofer, Carina',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-65', 'LO2035680', 'BORDER_COLLIE', 'MIND THE DOG CATTIVISSIMO ME', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'BALLI VALENTINA', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-66', 'ER38983/21', 'BORDER_COLLIE', 'Unlimited Star Olivia', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Maarit Hellman', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-67', 'DRC-G 2144794', 'GOLDEN_RETRIEVER', 'Culham Ash', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DE', 'Germany', 'Diana Strätling', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-68', 'LOE 2597335', 'BORDER_COLLIE', 'SMART AS A WHIP MAGNUM', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'ES', 'Spain', 'CÉSAR JOSÉ ARROYO GONZÁLEZ', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-69', 'DK18753/2023', 'BORDER_COLLIE', 'High working BC Ocean Eyes Maeglin', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'DK', 'Denmark', 'Miriam Søndergaard',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-70', 'CMKU/BOC/16325/21/24', 'BORDER_COLLIE', 'Dar Tarlet', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'CZ', 'Czechia', 'Petra Němcová', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-71', 'LOF BOR COL 43998/6822', 'BORDER_COLLIE', 'MIND THE DOG OAKLEY', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'FR', 'France', 'Cécile DOLIBOIS',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-72', 'RLŠVK BC 0060/24', 'BORDER_COLLIE', 'Spotting Peak Power Andria', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'LT', 'Lithuania', 'Gintarė Mačiulienė',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-73', 'NO38750/18', 'GOLDEN_RETRIEVER', 'Poecilia''s Push Pop', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'NO', 'Norway', 'Renate Lund', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-74', 'DK23353/2021', 'BORDER_COLLIE', 'Spotting Peak Power Marino', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DK', 'Denmark', 'Birgitta Ellgaard', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-75', 'I-115702', 'BORDER_COLLIE', 'FALCONER Reesheja', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PL', 'Poland', 'Elżbieta Kowalska', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-76', 'CMKU/BOC/12725/-19/19/21', 'BORDER_COLLIE', 'A Perfect Meissa Welshriverdee', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'CZ', 'Czechia', 'Dana Valešová',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-77', 'Col. 4944/22', 'BORDER_COLLIE', 'Fonix From Camilland''s', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'HU', 'Hungary', 'Nora Bartha', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-78', 'LOSH -1306851', 'BORDER_COLLIE', 'Tayco at Alba Eyes dit Teeguer', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'BE', 'Belgium', 'Waeytens Danielle',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-79', 'ÖHZB BORC 6285', 'BORDER_COLLIE', 'Mind the dog Afrodite', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AT', 'Austria', 'Florschütz, Monika', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-80', 'EST-01699/21', 'NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER', 'IRWLEND OIVALINE PIA', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'EE', 'Estonia', 'Kerli Mõtus',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-81', 'LOSH-1294385', 'BORDER_COLLIE', 'Sitka du Merle Blue', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'BE', 'Belgium', 'Rudy Franceschini', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-82', 'LOE 2633022', 'LABRADOR_RETRIEVER', 'D-PLUNDI EME VOM TROGENBACH', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'ES', 'Spain', 'RAFAEL CARLOS MARTÍNEZ RODRÍGUEZ',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-83', 'SHSB 785282', 'BORDER_COLLIE', 'Absinth''s Chilli Pepper', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'CH', 'Switzerland', 'Renate Tribus', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-84', 'LOE 2612972', 'BORDER_COLLIE', 'MIND THE DOG ARCHIMEDE', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'ES', 'Spain', 'MARIIA BIRG', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-85', 'I-118835', 'BORDER_COLLIE', 'High Tension LET''S PLAY', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PL', 'Poland', 'Daniela Makara', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-86', 'NO36750/18', 'BORDER_COLLIE', 'Hind Paw´s J-Jay', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'NO', 'Norway', 'Kristin Natås Hauger', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-87', 'CMKU/ZReg/BOC/16485/-22/21/24', 'BORDER_COLLIE', 'Imotz Arghala', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'CZ', 'Czechia', 'Alexandra Křivohlavá',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-88', 'PKR.VIII-38873', 'NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER',
        'I Am Miss Wildly Brave Unstoppable Dream ''Ginny''', NULL, 'k9x.support@gmail.com', 'k9x.support@gmail.com',
        'HU', 'Hungary', 'Anna Gergely', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-89', 'LŠVK BS 2425/19', 'BERNESE_MOUNTAIN_DOG', 'Lucky Star Pašilių Saulė', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'LT', 'Lithuania', 'Laurynas Janavičius',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-90', 'regv1230/2019', 'BORDER_COLLIE', 'Kajsaligans Amazing', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SE', 'Sweden', 'Michelle Holmlund', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-91', 'SHSB 761039', 'AUSTRALIAN_KELPIE', 'Boyd''s Bullriding Happy Yuko', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'CH', 'Switzerland', 'Janine Götz',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-92', 'LOP578157', 'BORDER_COLLIE', 'MIND THE DOG MIGNOLO', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PT', 'Portugal', 'MARCO JORGE RIBEIRO SILVA', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-93', 'DK23354/2021', 'BORDER_COLLIE', 'Spotting Peak Power Lovis', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DK', 'Denmark', 'Siri Renée Richter Jungersen',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-94', 'LOE 2399181', 'BORDER_COLLIE', 'ZIZOU DE XONNYDEBY', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'ES', 'Spain', 'ANTONIO AGUILAR RUEDA', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-95', 'VDH/BSD20 ML0089', 'MALINOIS', 'Studebaker`s Q`Louise', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DE', 'Germany', 'Santa Sofi', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-96', 'ÖHZB GR 8258', 'GOLDEN_RETRIEVER', 'Whispering Oaks Aranck', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AT', 'Austria', 'Besenböck, Nicole', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-97', 'DK18898/2019', 'BORDER_COLLIE', 'Kajsaligans Kommandusen', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DK', 'Denmark', 'Marie Louise Agerbak', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-98', 'JKC BCL-00548/22', 'BORDER_COLLIE', 'HWBC MONAKA OF REDDISH BROWN JP', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'JP', 'Japan', 'Noriko Sakano',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-99', 'EST-01991/17', 'BORDER_COLLIE', 'FAIR HELLOIZ DOLLY', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'EE', 'Estonia', 'Viivi Sepp', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-100', 'ADLA 003574', 'BORDER_COLLIE', 'Tending Knack', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AM', 'Armenia', 'Inna Bazhenova', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-101', 'LOSH - 01322959', 'BORDER_COLLIE', 'TIÊSTO MYSTEQUALBRAIN', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'BE', 'Belgium', 'DE CEUSTER EDDY', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-102', 'VDH/ZBrH BOC 23798', 'BORDER_COLLIE', 'Country Corner Ane Jean', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'DE', 'Germany', 'Carlotta Bohne',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-103', 'ISDS00/354527', 'BORDER_COLLIE', 'Kinloch Ella', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'NO', 'Norway', 'Anne Lise Ytreberg', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-104', 'ER16918/20', 'BORDER_COLLIE', 'Johan On Lio Messi JR', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Susanna Stark', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-105', 'LO19113589', 'BORDER_COLLIE', 'MIND THE DOG VIGOR', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'MORELLI FEDERICA', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-106', 'Regv1030/2020', 'BORDER_COLLIE', 'Härjavallens Magiska Vick', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SE', 'Sweden', 'Louise Karlgren', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-107', 'I-94645', 'BORDER_COLLIE', 'Reesheja CZIREAEL', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'PL', 'Poland', 'Kamila Buryn', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-108', 'CMKU/BOC/10356/17/21', 'BORDER_COLLIE', 'Aluca Esuatty', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'CZ', 'Czechia', 'Jana Krátká', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-109', 'DK01253/2020', 'BORDER_COLLIE', 'Cia', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'DK', 'Denmark', 'Helle Vittrup Thomsen', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-110', 'LOE 2619034', 'BORDER_COLLIE', 'MIND THE DOG RALPH LAUREN', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'ES', 'Spain', 'IVÁN JESÚS RAMIL VÁZQUEZ', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-111', 'LOF 40943/5082', 'BORDER_COLLIE', 'NO COMMENT DU DOMAINE DU BASCHBERRI', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'FR', 'France', 'Marion GALVAIRE',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-112', 'LO20140802', 'BORDER_COLLIE', 'Mind The Dog Roger Rabbit', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'IT', 'Italy', 'Cini Anna Maria', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-113', 'I-115195D', 'AUSTRALIAN_SHEPHERD', 'Collision Course CLOUD NINE', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'PL', 'Poland', 'Klaudia Szymańska',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-114', 'ÖHZB GR 9620', 'GOLDEN_RETRIEVER', 'Furry Ears Gundog Como', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'AT', 'Austria', 'Baumgartner, Johann', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-115', 'FI39472/19', 'BORDER_COLLIE', 'Demzina''s Lady In Black', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'FI', 'Finland', 'Minna Himanen', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-116', 'SPKP 1540', 'BORDER_COLLIE', 'Given to Fly Hardy origin', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'SK', 'Slovakia', 'Lucia Oláhová', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-117', 'SHSB 776395', 'BORDER_COLLIE', 'Cary Seven Sisters', NULL, 'k9x.support@gmail.com',
        'k9x.support@gmail.com', 'CH', 'Switzerland', 'Monika Ballerini', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE),
       ('wc2026-dog-118', 'LOF 41727/5368', 'BORDER_COLLIE', 'ONIL DES TERRES DE LA HARDT', NULL,
        'k9x.support@gmail.com', 'k9x.support@gmail.com', 'FR', 'France', 'Jean noël KERN',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, TRUE);

-- ---------------------------------------------------------------------------
-- 2) Judges (from the 'General' tab)
-- ---------------------------------------------------------------------------
INSERT INTO k9x.judges (id, name, creator, last_update, created_at, deleted_at, country)
VALUES ('wc2026-judge-1', 'Hanspeter Jutzi', 'k9x.support@gmail.com', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, 'DE'),
       ('wc2026-judge-2', 'Ingrid Tamášiová', 'k9x.support@gmail.com', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, 'SK'),
       ('wc2026-judge-3', 'Lukas Jansky', 'k9x.support@gmail.com', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, 'CZ'),
       ('wc2026-judge-4', 'Carin Bengtsson', 'k9x.support@gmail.com', FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, 'SE');

-- ---------------------------------------------------------------------------
-- 3) Competition
-- ---------------------------------------------------------------------------
INSERT INTO k9x.competitions (id, name, country, description, address, coord_alt, coord_long, creator,
                              last_update, created_at, deleted_at)
VALUES ('wc2026-comp', 'Ob World Cup 2026', 'SE', 'Obedience FCI World Champsionship 2026 ',
        'Mellersta Stenbocksgatan, 254 37 Helsingborg, Suecia', 56.049908, 12.707071, 'k9x.support@gmail.com',
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL);

-- ---------------------------------------------------------------------------
-- 4) Stages
-- ---------------------------------------------------------------------------
INSERT INTO k9x.stages (id, name, competition_id, date_from, date_to, creator, last_update, created_at,
                        deleted_at)
VALUES ('wc2026-stage-qualifications', 'Qualifications', 'wc2026-comp', 1782259200000, 1782604799999,
        'k9x.support@gmail.com', FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        NULL),
       ('wc2026-stage-final', 'Final', 'wc2026-comp', 1782604800000, 1782691199999,
        'k9x.support@gmail.com', FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        NULL);

-- ---------------------------------------------------------------------------
-- 5) Events (discipline OBDX = obedience)
-- ---------------------------------------------------------------------------
INSERT INTO k9x.events (id, discipline, configuration_id, score_calculation, name, creator, stage_id,
                        enrollment_deadline, last_update, created_at, deleted_at, awards)
VALUES ('wc2026-event-qualification-1', 'OBDX', 'OBDX_FCI_GRADE_3.V0', 'AVG', 'Qualification 1',
        'k9x.support@gmail.com', 'wc2026-stage-qualifications', NULL, FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, ARRAY ['CACIOB']),
       ('wc2026-event-qualification-2', 'OBDX', 'OBDX_FCI_GRADE_3.V0', 'AVG', 'Qualification 2',
        'k9x.support@gmail.com', 'wc2026-stage-qualifications', NULL, FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, ARRAY ['CACIOB']),
       ('wc2026-event-qualification-3', 'OBDX', 'OBDX_FCI_GRADE_3.V0', 'AVG', 'Qualification 3',
        'k9x.support@gmail.com', 'wc2026-stage-qualifications', NULL, FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM now()) * 1000), NULL, ARRAY ['CACIOB']),
       ('wc2026-event-final', 'OBDX', 'OBDX_FCI_GRADE_3.V0', 'AVG', 'Final', 'k9x.support@gmail.com',
        'wc2026-stage-final', NULL, FLOOR(EXTRACT(EPOCH FROM now()) * 1000), FLOOR(EXTRACT(EPOCH FROM now()) * 1000),
        NULL, ARRAY ['CACIOB']);

COMMIT;
